on:
  push:
    branches:
      - main
jobs:
  Deploy-GitHub-Pages-Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
