# ref to https://www.testmo.com/guides/github-actions-selenium
# must setup selenium services for github action ton success
on:
  pull_request
jobs:
  Tests:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: Install
        run: npm ci
      - name: Run Jest (lib tests)
        run: npm run test:lib
      - name: Run Jest (samples)
        run: CI=true SELENIUM_HUB_HOST=selenium npm run test:samples
