name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - uses: c-hive/gha-npm-cache@v1
      - run: npm i
      - run: git config --global user.email "$GITHUB_ACTOR@protonmail.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: git push --tags && git push
      - run: npm publish
    env:
     NODE_AUTH_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
