name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          registry-url: 'https://registry.npmjs.org'
      - uses: c-hive/gha-npm-cache@v1
      - run: npm publish
